### ISSUE TITLE
bug with spirit power and single card left in deck?

### ISSUE THREAD

**Issue by adolson** [rfunduk/onirim#2]
I couldn't think of a good title for this report, sorry.

OK, so I used a spirit power near the end of the draw deck. It showed me that the only card left was a god card, which I had the matching spirit card for in my hand (another spirit card, not the one I used to do the spirit power). That was apparently the only card left. I can't discard god cards, but I had no choice but to click it. It then said I lost? Shouldn't I have been able to not discard the god card, and not rearrange anything - basically would be the same as if I had noticed there was only one card left in the deck and just chose to discard the spirit card rather than using it. And then I'd draw the god card, and use the matching spirit card that I still had in my hand to win the game?

**Comment by rfunduk** [comment]
Hey, thanks for the report. I'm not actually sure this is a bug though. I think by 'spirit' you mean a key card, by 'spirit power' you mean discarding a key to start a prophecy, and by 'god card' you mean doors?

If so, then what you describe is correct:
- 1 card left in deck, it's a door
- at least 2 cards in hand, both keys, 1 same colour as door
- discard key/start prophecy
- prophecy shows door
- you must discard 1, you discard the door
- discarding a door = game over

Starting a prophecy with only 1 card in the deck is a very risky proposition! It might have been better to just PLAY the key that does not match the colour of the last door you need. If you couldn't do that because there was already a key at the top of the labyrinth... well, that's how it goes! :)

If I'm confused about what happened in your game, please feel free to write a test for the scenario that you think should pass but fails, and I'll attempt to either fix or clarify.

**Comment by adolson** [comment]
That is what happened, yes. But you normally can't discard a door, so that's what is confusing me. I didn't purposely use the spirit power with only one card remaining. I just didn't notice there was only one card left. I would have simply discarded it. Maybe a warning/confirmation if the deck has < 5 cards and you attempt to play a spirit ability/prophecy would help?

**Comment by rfunduk** [comment]
During a prophecy you _must_ discard a card. Normally you wouldn't discard a door, of course. But if the prophecy only has one card in it, you really have no choice :)

Also, you can't just discard keys. Discarding a key triggers a prophecy no matter what.

I'm not sure I want to add warnings and stuff. This is meant to be a straight implementation of the physical card game. It's up to the player to strategize when to start a prophecy or not. It's a totally legit thing to do, just risky when there are so few cards in the deck.

**Comment by adolson** [comment]
Ah, well, I could have just played the key/spirit, then. Just didn't realize the card count. I never would have done such a stupid maneuver in Onirim. Oh well.
